name: Deploy Web.html

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Pages
        uses: actions/setup-pages@v2

      - name: Copy Web.html to root
        run: cp html/Web.html $GITHUB_WORKSPACE

      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Web.html
          git commit -m 'Deploy Web.html'
          git push origin HEAD:gh-pages
