name: Deploy Web.html

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發部署

permissions:
  contents: write  # 允許對 repository 的內容進行更改

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 檢查出程式碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 準備部署目錄
      - name: Copy Web.html to root
        run: |
          mkdir -p $GITHUB_WORKSPACE/gh-pages
          cp html/Web.html $GITHUB_WORKSPACE/gh-pages

      # 3. 部署到 gh-pages 分支
      - name: Deploy to GitHub Pages
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git init
          git add .
          git commit -m 'Deploy Web.html'
          git branch -M gh-pages
          git remote add origin https://github.com/${{ github.repository }}
          git push --force origin gh-pages
