name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # 當 main 分支有更新時部署

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 檢出程式碼
      - uses: actions/checkout@v4

      # 2. 如果有需要執行 npm build 或其他建置流程，在這裡進行
      #    若只是純靜態檔案，可直接將檔案複製到指定目錄。
      - name: Prepare artifact
        run: |
          mkdir -p public
          cp html/index.html public/index.html

      # 3. 上傳產物
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
    steps:
      # 4. 部署靜態網站到 GitHub Pages
      - uses: actions/deploy-pages@v2
