name: Deploy Web.html

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Remove existing .git
        run: rm -rf .git

      - name: Copy Web.html to gh-pages folder
        run: |
          mkdir -p gh-pages
          cp html/Web.html gh-pages/

      - name: Deploy to GitHub Pages
        run: |
          git init
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add gh-pages/Web.html
          git commit -m 'Deploy Web.html'
          git branch -M gh-pages
          git remote add origin https://github.com/${{ github.repository }}
          git push --force origin gh-pages
