name: Deploy Web.html

on:
  push:
    branches:
      - main  # 當推送到 main 分支時觸發部署

permissions:
  contents: write  # 允許對 Repository 的內容進行更改

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 檢查出程式碼
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 準備部署目錄
      - name: Prepare gh-pages directory
        run: |
          mkdir -p gh-pages
          cp html/Web.html gh-pages/

      # 3. 初始化 Git 並推送到 gh-pages
      - name: Deploy to GitHub Pages
        run: |
          cd gh-pages
          git init
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy Web.html"
          # 設置或更新遠端 URL
          git remote set-url origin https://github.com/${{ github.repository }} || git remote add origin https://github.com/${{ github.repository }}
          git branch -M gh-pages
          git push --force origin gh-pages
