name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]  # 當 main 分支有更新時部署

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages-deploy"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 檢出程式碼
      - uses: actions/checkout@v3

      # 2. 建置靜態網站（依需求調整建置流程）
      - name: Build static site
        run: |
          mkdir -p public
          cp static_html/index.html public/index.html

      # 3. 上傳建置產物供部署工作使用
      - name: Upload artifact for deployment job
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      # 4. 部署靜態網站到 GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
